name: Erlang CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: make
    - name: Run tests
      run: make test
